### ISSUE TITLE
Where does the app get installed and how to launch it ?

### ISSUE THREAD

**Issue by ishandutta2007** [LemmaSoftware/akvo#5]
Where does the app install and how to launch it ?

I have installed using
```
pip3 install pyqt-distutils
python3 setup.py build 
python3 setup.py install

```

**Comment by tirons** [comment]
What operating system are you using? It will be installed wherever python prefers to install it, and should be added to your path automatically.

**Comment by ishandutta2007** [comment]
> What operating system are you using? It will be installed wherever python prefers to install it, and should be added to your path automatically.

macOS High Sierra

**Comment by ishandutta2007** [comment]
Here is my full tree after running the above commands, now tell me how do I launch the app,


.
├── Akvo.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── requires.txt
│   └── top_level.txt
├── INSTALL.txt
├── LICENCE
├── LICENSE
├── README.md
├── _config.yml
├── akvo
│   ├── __init__.py
│   ├── gui
│   │   ├── Loop.ui
│   │   ├── __init__.py
│   │   ├── addCircularLoop.ui
│   │   ├── addCircularLoop_ui.py
│   │   ├── addFigure8Loop.ui
│   │   ├── addFigure8Loop_ui.py
│   │   ├── addPolygonalLoop.ui
│   │   ├── addPolygonalLoop_ui.py
│   │   ├── akvo-about.png
│   │   ├── akvo-crop.png
│   │   ├── akvo.png
│   │   ├── akvo2.png
│   │   ├── akvoGUI.py
│   │   ├── callScript.py
│   │   ├── logo.py
│   │   ├── main-bu.ui
│   │   ├── main.ui
│   │   ├── main2ui.py
│   │   ├── main_ui.py
│   │   ├── mainbu.ui
│   │   ├── mainui2.py
│   │   ├── mydynamicmplcanvas.py
│   │   ├── mydynamicmplcanvasnavigator.py
│   │   ├── quad.r
│   │   ├── redirect.ui
│   │   ├── redirect_ui.py
│   │   ├── replace.sh
│   │   ├── scroll.ui
│   │   ├── temp.py
│   │   └── turtle.png
│   ├── terminal
│   │   ├── SEGPlot.py
│   │   ├── USGSPlots.py
│   │   ├── epsPlots.py
│   │   ├── plotKernel.py
│   │   ├── plotKernelDiff.py
│   │   ├── plotyaml.py
│   │   └── tempPlots.py
│   ├── tressel
│   │   ├── SlidesPlot.py
│   │   ├── __init__.py
│   │   ├── adapt.py
│   │   ├── cadapt.pyx
│   │   ├── calcAkvoKernel.py
│   │   ├── cmaps.py
│   │   ├── cpca.pyx
│   │   ├── decay.py
│   │   ├── filtfilt.py
│   │   ├── harmonic.py
│   │   ├── invertTA.py
│   │   ├── lemma_yaml.py
│   │   ├── logbarrier.py
│   │   ├── mrsurvey.py
│   │   ├── pca.py
│   │   ├── rotate.py
│   │   └── smooth.py
│   └── xml
│       ├── usgsXML.py
│       ├── utClasses.py
│       └── utLoadAkvoProc.py
├── akvologo.svg
├── bir.sh
├── build
│   ├── bdist.macosx-10.13-x86_64
│   └── lib
│       └── akvo
│           ├── __init__.py
│           ├── gui
│           │   ├── Loop.ui
│           │   ├── __init__.py
│           │   ├── addCircularLoop.ui
│           │   ├── addCircularLoop_ui.py
│           │   ├── addFigure8Loop.ui
│           │   ├── addFigure8Loop_ui.py
│           │   ├── addPolygonalLoop.ui
│           │   ├── addPolygonalLoop_ui.py
│           │   ├── akvoGUI.py
│           │   ├── callScript.py
│           │   ├── logo.py
│           │   ├── main-bu.ui
│           │   ├── main.ui
│           │   ├── main2ui.py
│           │   ├── main_ui.py
│           │   ├── mainbu.ui
│           │   ├── mainui2.py
│           │   ├── mydynamicmplcanvas.py
│           │   ├── mydynamicmplcanvasnavigator.py
│           │   ├── redirect.ui
│           │   ├── redirect_ui.py
│           │   ├── scroll.ui
│           │   └── temp.py
│           └── tressel
│               ├── SlidesPlot.py
│               ├── __init__.py
│               ├── adapt.py
│               ├── calcAkvoKernel.py
│               ├── cmaps.py
│               ├── decay.py
│               ├── filtfilt.py
│               ├── harmonic.py
│               ├── invertTA.py
│               ├── lemma_yaml.py
│               ├── logbarrier.py
│               ├── mrsurvey.py
│               ├── pca.py
│               ├── rotate.py
│               └── smooth.py
├── dist
│   └── Akvo-1.4.6-py3.7.egg
├── publish.sh
├── pyuic.json
└── setup.py

13 directories, 114 files

**Comment by tirons** [comment]
Just type "avko" in your terminal. It looks like everything installed correctly.

**Comment by tirons** [comment]
Is this resolved? Can we close this?

**Comment by tirons** [comment]
I'm closing, feel free to reopen if you are having problems.
